Repository corda/corda-runtime-os, pull requests merged in 2023-10, with the labels that each got.

#4774 CORE-16234: For persistence api add endpoint and change naming of existing endpoint
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/processor/impl/LedgerPersistenceRequestSubscriptionFactoryImpl.kt
  components/ledger/ledger-verification/src/main/kotlin/net/corda/ledger/verification/processor/impl/VerificationSubscriptionFactoryImpl.kt
  components/persistence/entity-processor-service-impl/build.gradle
  components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
  components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceServiceInternalTests.kt
  components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/helpers/Utils.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/EntityProcessorImpl.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/EntityRequestSubscriptionFactoryImpl.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/FlowPersistenceServiceImpl.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityRequestProcessor.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityRpcRequestProcessor.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/ProcessorService.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/Utils.kt
  components/persistence/entity-processor-service-impl/src/test/kotlin/net/corda/entityprocessor/impl/EntityProcessorFactoryImplTest.kt
  components/persistence/entity-processor-service-impl/src/test/kotlin/net/corda/entityprocessor/impl/EntityRequestSubscriptionFactoryImplTest.kt
  components/persistence/entity-processor-service/build.gradle
  components/persistence/entity-processor-service/src/main/kotlin/net/corda/entityprocessor/EntityProcessor.kt
  components/persistence/entity-processor-service/src/main/kotlin/net/corda/entityprocessor/EntityProcessorFactory.kt
  components/persistence/entity-processor-service/src/main/kotlin/net/corda/entityprocessor/EntityRequestSubscriptionFactory.kt
  components/uniqueness/uniqueness-checker-impl/src/main/kotlin/net/corda/uniqueness/checker/impl/BatchedUniquenessCheckerLifecycleImpl.kt
Labels: enhancement

#4763 CORE-16419 - template, schema and values yaml changes to support isolated state manager db
  .ci/e2eTests/corda.yaml
  charts/corda-lib/templates/_bootstrap.tpl
  charts/corda-lib/templates/_helpers.tpl
  charts/corda-lib/templates/_worker.tpl
  charts/corda/templates/secrets.yaml
  charts/corda/values.schema.json
  charts/corda/values.yaml
  state-manager-postgres.yaml
  state-manager.yaml
  tools/plugins/db-config/src/main/kotlin/net/corda/cli/plugins/dbconfig/Spec.kt
  tools/plugins/db-config/src/test/kotlin/net/corda/cli/plugins/dbconfig/SpecTest.kt
  values-prereqs.yaml
Labels: 5.1

#4856 CORE-16203, CORE-17429: Flow changes revert
  components/flow/flow-mapper-service/src/integrationTest/kotlin/net/corda/session/mapper/service/integration/TestFlowMessageProcessor.kt
  components/flow/flow-mapper-service/src/main/kotlin/net/corda/session/mapper/service/executor/FlowMapperMessageProcessor.kt
  components/flow/flow-mapper-service/src/test/kotlin/net/corda/session/mapper/service/executor/FlowMapperMessageProcessorTest.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/context/FlowServiceTestContext.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/context/OutputAssertionsImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/messaging/mediator/FlowEventMediatorFactoryImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/converters/impl/FlowEventContextConverterImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/factory/FlowEventPipelineFactory.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/factory/impl/FlowEventPipelineFactoryImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/service/FlowExecutorImpl.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/RequestHandlerTestContext.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/converters/FlowEventContextConverterImplTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/factory/FlowEventPipelineFactoryImplTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/impl/FlowEventProcessorImplTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/service/FlowExecutorImplTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/test/utils/FlowEventContextHelper.kt
  components/ledger/ledger-utxo-token-cache/src/main/kotlin/net/corda/ledger/utxo/token/cache/services/TokenCacheEventProcessor.kt
  components/ledger/ledger-utxo-token-cache/src/test/kotlin/net/corda/ledger/utxo/token/cache/impl/services/TokenCacheEventProcessorTest.kt
  components/link-manager/src/main/kotlin/net/corda/p2p/linkmanager/delivery/DeliveryTracker.kt
  components/link-manager/src/test/kotlin/net/corda/p2p/linkmanager/delivery/DeliveryTrackerTest.kt
  components/membership/membership-persistence-service-impl/src/main/kotlin/net/corda/membership/impl/persistence/service/MembershipPersistenceAsyncProcessor.kt
  components/membership/membership-persistence-service-impl/src/test/kotlin/net/corda/membership/impl/persistence/service/MembershipPersistenceAsyncProcessorTest.kt
  components/membership/membership-service-impl/src/main/kotlin/net/corda/membership/service/impl/CommandsRetryManager.kt
  components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/RegistrationProcessor.kt
  components/membership/registration-impl/src/test/kotlin/net/corda/membership/impl/registration/dynamic/RegistrationProcessorTest.kt
  libs/flows/flow-api/src/main/kotlin/net/corda/flow/pipeline/events/FlowEventContext.kt
  libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/consumer/DBCordaConsumerImpl.kt
  libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/consumer/CordaKafkaConsumerImpl.kt
  libs/messaging/kafka-message-bus-impl/src/test/kotlin/net/corda/messagebus/kafka/consumer/CordaKafkaConsumerImplTest.kt
  libs/messaging/message-bus/src/main/kotlin/net/corda/messagebus/api/consumer/CordaConsumer.kt
  libs/messaging/messaging-impl/build.gradle
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/ClientTask.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/MessageBusClient.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/MessageBusConsumer.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/MultiSourceEventMediatorImpl.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/ProcessorTask.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/StateManagerHelper.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/taskmanager/TaskManagerImpl.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/ClientTaskTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/MessageBusClientTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/MessageBusConsumerTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/MultiSourceEventMediatorImplTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/ProcessorTaskTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/StateManagerHelperTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/TaskManagerHelperTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/factory/MediatorComponentFactoryTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImplTest.kt
  libs/messaging/messaging/build.gradle
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/MediatorConsumer.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/MessagingClient.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/processor/StateAndEventProcessor.kt
  testing/message-patterns/src/integrationTest/kotlin/net/corda/messaging/integration/processors/TestStateEventProcessor.kt
  testing/message-patterns/src/integrationTest/kotlin/net/corda/messaging/integration/processors/TestStateEventProcessorStrings.kt
  testing/p2p/inmemory-messaging-impl/src/integrationTest/kotlin/net/corda/messaging/emulation/subscription/stateandevent/InMemoryStateAndEventSubscriptionIntegrationTests.kt
  testing/p2p/inmemory-messaging-impl/src/main/kotlin/net/corda/messaging/emulation/subscription/stateandevent/EventSubscription.kt
  testing/p2p/inmemory-messaging-impl/src/test/kotlin/net/corda/messaging/emulation/subscription/stateandevent/EventSubscriptionTest.kt
  testing/p2p/inmemory-messaging-impl/src/test/kotlin/net/corda/messaging/emulation/subscription/stateandevent/StateSubscriptionTest.kt
Labels: 5.1

#4861 CORE-17747 remove attachments
  components/ledger/ledger-utxo-flow/src/integrationTest/kotlin/net/corda/ledger/utxo/flow/impl/transaction/filtered/tests/UtxoFilteredTransactionTest.kt
  components/ledger/ledger-utxo-flow/src/integrationTest/kotlin/net/corda/ledger/utxo/flow/impl/transaction/serializer/tests/UtxoFilteredTransactionAMQPSerializationTest.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoBaselinedTransactionBuilder.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoTransactionBuilderContainer.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoTransactionBuilderData.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoTransactionBuilderImpl.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoTransactionBuilderInternal.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/factory/impl/UtxoSignedTransactionFactoryImpl.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/UtxoLedgerServiceImplTest.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactionbuilder/v1/ReceiveAndUpdateTransactionBuilderFlowV1Test.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/transactionbuilder/v1/SendTransactionBuilderDiffFlowV1Test.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoBaselinedTransactionBuilderDiffTest.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoLedgerTransactionImplTest.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoTransactionBuilderImplAppendTest.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/transaction/UtxoTransactionBuilderImplTest.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/transaction/serializer/amqp/UtxoSignedTransactionSerializerTest.kt
  gradle.properties
  libs/ledger/ledger-utxo-data/src/main/kotlin/net/corda/ledger/utxo/data/transaction/UtxoComponentGroup.kt
  libs/ledger/ledger-utxo-data/src/main/kotlin/net/corda/ledger/utxo/data/transaction/UtxoLedgerTransactionImpl.kt
  libs/ledger/ledger-utxo-data/src/main/kotlin/net/corda/ledger/utxo/data/transaction/WrappedUtxoWireTransaction.kt
Labels: 5.1

#4709 CORE-16181 Implement RPC Producer that implements RPC client
  charts/corda-lib/templates/_worker.tpl
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/RPCClient.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/MessagingClientFactoryFactoryImpl.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/RPCClientFactory.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/utils/HTTPRetryConfig.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/utils/HTTPRetryExecutor.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/RPCClientTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/factory/MessagingClientFactoryFactoryTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/factory/RPCClientFactoryTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/utils/HTTPRetryExecutorTest.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/exception/CordaRestAPIExceptions.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/factory/MessagingClientFactoryFactory.kt
Labels: 5.1

#4837 CORE-15552 Add `findUnconsumedStatesByExactType` paging API
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/registration/impl/VaultNamedQueryFactoryProvider.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/UtxoPersistenceService.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/UtxoRepository.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoQueryProvider.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoRepositoryImpl.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoRequestHandlerSelectorImpl.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/request/handlers/UtxoFindUnconsumedStatesByExactTypeRequestHandler.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/UtxoLedgerServiceImpl.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/persistence/LedgerPersistenceMetricOperationName.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/persistence/UtxoLedgerStateQueryService.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/persistence/UtxoLedgerStateQueryServiceImpl.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/persistence/external/events/FindUnconsumedStatesByExactTypeExternalEventFactory.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/persistence/external/events/FindUnconsumedStatesByExactTypeExternalEventFactoryTest.kt
  gradle.properties
Labels: 5.1

#4731 CORE-17487 Parallel flow pipeline and Task Manager
  components/flow/flow-mapper-service/src/main/kotlin/net/corda/session/mapper/messaging/mediator/FlowMapperEventMediatorFactoryImpl.kt
  components/flow/flow-mapper-service/src/test/kotlin/net/corda/session/mapper/service/messaging/mediator/FlowMapperEventMediatorFactoryImplTest.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/fiber/factory/FlowFiberFactoryImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/messaging/mediator/FlowEventMediatorFactoryImpl.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/messaging/FlowEventMediatorFactoryImplTest.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/verifier/UtxoLedgerTransactionVerificationServiceImpl.kt
  libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/producer/CordaKafkaProducerImpl.kt
  libs/messaging/messaging-impl/build.gradle
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/MultiSourceEventMediatorImpl.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/TaskManagerHelper.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/MultiSourceEventMediatorFactoryImpl.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/statemanager/StateManagerImpl.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/taskmanager/TaskManagerImpl.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/StateAndEventSubscriptionImpl.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/subscription/consumer/StateAndEventConsumerImpl.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/MultiSourceEventMediatorImplTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/TaskManagerHelperTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/factory/MultiSourceEventMediatorFactoryTest.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/config/EventMediatorConfig.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/config/EventMediatorConfigBuilder.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/taskmanager/TaskManager.kt
  libs/metrics/src/main/kotlin/net/corda/metrics/CordaMetrics.kt
  libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/KryoCheckpointSerializer.kt
  libs/serialization/serialization-kryo/src/main/kotlin/net/corda/kryoserialization/impl/KryoCheckpointSerializerBuilderImpl.kt
  libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/KryoCheckpointSerializerTest.kt
  libs/serialization/serialization-kryo/src/test/kotlin/net/corda/kryoserialization/serializers/SingletonSerializeAsTokenSerializerTest.kt
  libs/task-manager/build.gradle
  libs/task-manager/src/main/java/net/corda/taskmanager/package-info.java
  libs/task-manager/src/main/kotlin/net/corda/taskmanager/TaskManager.kt
  libs/task-manager/src/main/kotlin/net/corda/taskmanager/TaskManagerFactory.kt
  libs/task-manager/src/main/kotlin/net/corda/taskmanager/impl/CordaExecutorServiceWrapper.kt
  libs/task-manager/src/main/kotlin/net/corda/taskmanager/impl/TaskManagerFactoryImpl.kt
  libs/task-manager/src/main/kotlin/net/corda/taskmanager/impl/TaskManagerImpl.kt
  libs/task-manager/src/test/kotlin/net/corda/taskmanager/impl/TaskManagerImplTest.kt
  settings.gradle
Labels: 5.1

#4820 CORE-16242 - Synchronous RPC Pattern API Implementation for Crypto Worker
  applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/services/CryptoRPCSmokeTests.kt
  components/crypto/crypto-service-impl/src/main/java/net/corda/crypto/service/impl/rpc/package-info.java
  components/crypto/crypto-service-impl/src/main/kotlin/net/corda/crypto/service/impl/rpc/CryptoFlowOpsRpcProcessor.kt
  components/crypto/crypto-service-impl/src/test/kotlin/net/corda/crypto/service/impl/rpc/CryptoFlowOpsRpcProcessorTests.kt
  processors/crypto-processor/src/main/kotlin/net/corda/processors/crypto/internal/CryptoProcessorImpl.kt
Labels: 5.1

#4854 CORE-17514 Change the Link Manager to handle bad group policy
  components/link-manager/src/main/kotlin/net/corda/p2p/linkmanager/common/MessageConverter.kt
  components/link-manager/src/main/kotlin/net/corda/p2p/linkmanager/delivery/InMemorySessionReplayer.kt
  components/link-manager/src/main/kotlin/net/corda/p2p/linkmanager/outbound/OutboundMessageProcessor.kt
  components/link-manager/src/main/kotlin/net/corda/p2p/linkmanager/sessions/SessionManagerImpl.kt
  components/link-manager/src/main/kotlin/net/corda/p2p/linkmanager/sessions/SessionManagerWarnings.kt
  components/link-manager/src/test/kotlin/net/corda/p2p/linkmanager/common/MessageConverterTest.kt
  components/link-manager/src/test/kotlin/net/corda/p2p/linkmanager/delivery/InMemorySessionReplayerTest.kt
  components/link-manager/src/test/kotlin/net/corda/p2p/linkmanager/outbound/OutboundMessageProcessorTest.kt
  components/link-manager/src/test/kotlin/net/corda/p2p/linkmanager/sessions/SessionManagerTest.kt
  components/membership/group-policy-impl/src/main/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImpl.kt
  components/membership/group-policy-impl/src/test/kotlin/net/corda/membership/impl/grouppolicy/GroupPolicyProviderImplTest.kt
  libs/membership/membership-common/src/main/kotlin/net/corda/membership/lib/grouppolicy/GroupPolicy.kt
  libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/MGMGroupPolicyImpl.kt
  libs/membership/membership-impl/src/test/kotlin/net/corda/membership/lib/impl/grouppolicy/v1/MGMGroupPolicyImplTest.kt
Labels: 5.1

#4901 CORE-17779 add metric for a HTTP RPC Client request
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/RPCClient.kt
  libs/metrics/src/main/kotlin/net/corda/metrics/CordaMetrics.kt
Labels: Topology Redesign, 5.1
