Repository corda/corda-runtime-os, pull requests merged in 2023-07, with the labels that each got.

#4203 CORE-15096: Optimise regex for array class names.
  libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/utilities/BundleUtils.kt
Labels: enhancement

#4225 CORE-15177 Fix for Facade unit tests checking 'shouldFailToBindWith' give false positives
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/services/interop/binding/BindingAssertions.kt
Labels: WIP

#4231 CORE-15303: Remove Kotlin reflection from UtxoFinalityFlowV1.
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/finality/v1/UtxoFinalityFlowV1.kt
Labels: bug

#4251 CORE-14685: Separate UniquenessChecker and BackingStore from Lifecycle.
  components/uniqueness/backing-store-impl/src/backingStoreBenchmark/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplBenchmark.kt
  components/uniqueness/backing-store-impl/src/integrationTest/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplIntegrationTests.kt
  components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImpl.kt
  components/uniqueness/backing-store-impl/src/main/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreLifecycleImpl.kt
  components/uniqueness/backing-store-impl/src/test/kotlin/net/corda/uniqueness/backingstore/impl/JPABackingStoreImplTests.kt
  components/uniqueness/backing-store/src/main/kotlin/net/corda/uniqueness/backingstore/BackingStore.kt
  components/uniqueness/uniqueness-checker-client-service-impl/build.gradle
  components/uniqueness/uniqueness-checker-client-service-impl/src/main/kotlin/net/corda/uniqueness/client/impl/UniquenessCheckClientExternalEventFactory.kt
  components/uniqueness/uniqueness-checker-impl-osgi-tests/src/integrationTest/kotlin/net/corda/uniqueness/checker/impl/osgitests/MessageBusIntegrationTests.kt
  components/uniqueness/uniqueness-checker-impl/build.gradle
  components/uniqueness/uniqueness-checker-impl/src/integrationTest/kotlin/net/corda/uniqueness/checker/impl/UniquenessCheckerImplDBIntegrationTests.kt
  components/uniqueness/uniqueness-checker-impl/src/main/kotlin/net/corda/uniqueness/checker/impl/BatchedUniquenessCheckerImpl.kt
  components/uniqueness/uniqueness-checker-impl/src/main/kotlin/net/corda/uniqueness/checker/impl/BatchedUniquenessCheckerLifecycleImpl.kt
  components/uniqueness/uniqueness-checker-impl/src/test/kotlin/net/corda/uniqueness/checker/impl/UniquenessCheckerImplTests.kt
  components/uniqueness/uniqueness-checker/src/main/kotlin/net/corda/uniqueness/checker/UniquenessChecker.kt
  processors/uniqueness-processor/src/main/kotlin/net/corda/processors/uniqueness/internal/UniquenessProcessorImpl.kt
  testing/uniqueness/backing-store-fake/src/main/kotlin/net/corda/uniqueness/backingstore/impl/fake/BackingStoreImplFake.kt
Labels: enhancement

#4263 CORE-14685: Add support for UTXO flows.
  build.gradle
  components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/PrivateKeyService.kt
  components/crypto/crypto-softhsm-impl/src/main/kotlin/net/corda/crypto/softhsm/impl/DriverCryptoServiceProviderImpl.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/transaction/verifier/UtxoLedgerTransactionVerificationServiceImpl.kt
  gradle.properties
  libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/GroupParametersFactoryImpl.kt
  libs/membership/membership-impl/src/main/kotlin/net/corda/membership/lib/impl/SignedGroupParametersImpl.kt
  testing/cpbs/ledger-utxo-demo-app/src/main/kotlin/com/r3/corda/demo/utxo/UtxoDemoFlow.kt
  testing/driver/driver-engine/build.gradle
  testing/driver/driver-engine/src/main/java/net/corda/testing/driver/crypto/package-info.java
  testing/driver/driver-engine/src/main/java/net/corda/testing/driver/sandbox/package-info.java
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/config/SmartConfigProvider.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DbConnectionManagerImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/ExternalProcessor.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/flow/RunFlowImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/ExternalProcessor.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/crypto/CryptoProcessor.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/crypto/MemoryWrappingRepository.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/crypto/SigningKeyProvider.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/entity/EntityProcessor.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/ledger/LedgerProcessor.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/uniqueness/UniquenessProcessor.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/verify/VerifyProcessor.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/Constants.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/CpkReadServiceImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/EmbeddedNodeServiceImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/GroupPolicyProviderImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/MembershipGroupReaderProviderImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/VirtualNodeLoaderImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/VirtualNodeServiceImpl.kt
  testing/driver/driver-engine/test.bndrun
  testing/driver/driver-testing/build.gradle
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/AMQPSerializationTests.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/FlowDriverTest.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/FlowTests.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/NotaryFlowTests.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/UtxoLedgerTests.kt
  testing/driver/driver-testing/src/test/kotlin/net/corda/testing/driver/tests/DriverTest.kt
  testing/driver/src/main/java/net/corda/testing/driver/AbstractDriver.java
  testing/driver/src/main/java/net/corda/testing/driver/AllTestsDriver.java
  testing/driver/src/main/java/net/corda/testing/driver/DriverNodes.java
  testing/driver/src/main/java/net/corda/testing/driver/EachTestDriver.java
  testing/driver/src/main/java/net/corda/testing/driver/node/EmbeddedNodeService.java
  testing/driver/src/main/java/net/corda/testing/driver/node/FlowErrorException.java
  testing/driver/src/main/java/net/corda/testing/driver/node/FlowFatalException.java
  testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverDSLImpl.kt
Labels: enhancement

#4293 CORE-14685: Refactor driver only to create a single OSGi framework.
  buildSrc/src/main/groovy/corda.driver-tests.gradle
  testing/driver/README.md
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/crypto/CryptoProcessor.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/crypto/SigningKeyProvider.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/Constants.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/CpiLoader.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/EmbeddedNodeServiceImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/VirtualNodeLoaderImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/sandbox/VirtualNodeServiceImpl.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/AMQPSerializationTests.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/ConsensualLedgerTests.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/FlowDriverTest.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/FlowTests.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/NotaryFlowTests.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/UtxoLedgerTests.kt
  testing/driver/driver-testing/src/test/kotlin/net/corda/testing/driver/tests/DriverTest.kt
  testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
  testing/driver/src/main/java/net/corda/testing/driver/impl/DriverInternalDSL.java
  testing/driver/src/main/java/net/corda/testing/driver/node/EmbeddedNodeService.java
  testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverDSLImpl.kt
  testing/driver/src/main/kotlin/net/corda/testing/driver/impl/FlowRunner.kt
Labels: enhancement

#4311 CORE-8434: Disable services which sandbox testing needs to override.
  testing/sandboxes-testkit/src/main/kotlin/net/corda/testing/sandboxes/testkit/impl/SandboxGroupContextComponentImpl.kt
  testing/sandboxes-testkit/src/main/kotlin/net/corda/testing/sandboxes/testkit/impl/VirtualNodeServiceImpl.kt
  testing/sandboxes/src/main/kotlin/net/corda/testing/sandboxes/SandboxSetup.kt
  testing/sandboxes/src/main/kotlin/net/corda/testing/sandboxes/impl/CpiInfoServiceImpl.kt
  testing/sandboxes/src/main/kotlin/net/corda/testing/sandboxes/impl/CpkReadServiceImpl.kt
  testing/sandboxes/src/main/kotlin/net/corda/testing/sandboxes/impl/MembershipGroupReaderProviderImpl.kt
  testing/sandboxes/src/main/kotlin/net/corda/testing/sandboxes/impl/SandboxSetupImpl.kt
  testing/sandboxes/src/main/kotlin/net/corda/testing/sandboxes/impl/VirtualNodeLoaderImpl.kt
Labels: bug

#4346 CORE-15660: Use fewer database connections, and close them afterwards.
  components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/asyncoperation/utility/MigrationUtilityImpl.kt
  testing/db-testkit/src/main/kotlin/net/corda/db/testkit/DatabaseInstaller.kt
  testing/persistence-testkit/src/main/kotlin/net/corda/db/persistence/testkit/components/VirtualNodeService.kt
Labels: bug

#4353 CORE-8434: Create an OSGi requirement for sandboxes-testkit.
  testing/persistence-testkit/src/main/kotlin/net/corda/db/persistence/testkit/components/VirtualNodeService.kt
  testing/sandboxes-testkit/src/main/java/net/corda/testing/sandboxes/testkit/RequireSandboxTestkit.java
  testing/sandboxes-testkit/src/main/java/net/corda/testing/sandboxes/testkit/package-info.java
Labels: bug

#4368 CORE-15770: Update CLI plugin's SqlFormatter to understand Hibernate property access.
  tools/plugins/initial-config/src/main/kotlin/net/corda/cli/plugin/initialconfig/SqlFormatters.kt
  tools/plugins/initial-config/src/test/kotlin/net/corda/cli/plugin/initialconfig/TestSqlFormattersForFieldAccess.kt
  tools/plugins/initial-config/src/test/kotlin/net/corda/cli/plugin/initialconfig/TestSqlFormattersForPropertyAccess.kt
Labels: enhancement

#4384 CORE-15833: Fix parsing of (:parameter) and (**::int) for custom queries.
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/expressions/PostgresVaultNamedQueryExpressionParser.kt
  components/ledger/ledger-persistence/src/test/kotlin/net/corda/ledger/persistence/query/impl/parsing/expressions/PostgresVaultNamedQueryExpressionParserTest.kt
Labels: bug
