Repository corda/corda-runtime-os, pull requests merged in 2023-02, with the labels that each got.

#3037 CORE-8335: Stop logging DEBUG message when sandbox cannot load class.
  libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/SandboxGroupImpl.kt
  libs/sandbox-internal/src/main/kotlin/net/corda/sandbox/internal/sandbox/CpkSandboxImpl.kt
Labels: enhancement

#3032 CORE-9044: Flow REST endpoint validation on flow_start_operational_status
  applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/virtualnode/VirtualNodeRpcTest.kt
  components/flow/flow-rpcops-service-impl/src/main/kotlin/net/corda/flow/rpcops/impl/v1/FlowRestResourceImpl.kt
  testing/e2e-test-utilities/src/main/kotlin/net/corda/e2etest/utilities/FlowTestUtils.kt
Labels: WIP

#3085 CORE-9580: Ignore activation of fragment bundles at start-up.
  osgi-framework-bootstrap/src/main/java/net/corda/osgi/framework/OSGiFrameworkWrap.java
Labels: bug

#3094 CORE-10198: Upgrade Kotlin Metadata library 0.5 -> 0.6.
  gradle.properties
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/impl/KotlinClassImpl.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KotlinFunction.kt
Labels: enhancement

#3220 CORE-9684: FlowStatusResponse.timestamp returns current time
  components/flow/flow-rpcops-service-impl/src/main/kotlin/net/corda/flow/rpcops/impl/factory/MessageFactoryImpl.kt
  components/flow/flow-rpcops-service-impl/src/test/kotlin/net/corda/flow/rpcops/impl/factory/MessageFactoryImplTest.kt
Labels: bug

#3259 CORE-11069: Hot-fix for Kotlin reflection memory leak.
  libs/kotlin-heap-fix/build.gradle
  libs/kotlin-heap-fix/src/main/java/net/corda/kotlin/reflect/heap/KotlinHeapFixer.java
  libs/kotlin-heap-fix/src/main/java/net/corda/kotlin/reflect/heap/package-info.java
  libs/kotlin-heap-fix/src/main/resources/net/corda/kotlin/reflect/heap/configuration.properties
  libs/sandbox-hooks/build.gradle
  libs/sandbox-hooks/src/main/kotlin/net/corda/sandboxhooks/register/Registration.kt
  settings.gradle
Labels: bug

#3017 CORE-9486: local sandboxes based on cpi from checkpoint
  applications/examples/sandbox-app/src/main/kotlin/net/corda/example/vnode/CordaVNode.kt
  applications/examples/sandbox-app/src/main/kotlin/net/corda/example/vnode/VNodeService.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/FlowFinishedAcceptanceTest.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/StartFlowTest.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/CheckpointInitializer.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/factory/impl/FlowFiberExecutionContextFactoryImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandler.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/events/StartFlowEventHandler.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/service/InitiateFlowRequestService.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/FlowSandboxService.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sandbox/impl/FlowSandboxServiceImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sessions/CheckpointInitializerImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sessions/FlowProtocolStoreFactory.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sessions/impl/FlowProtocolStoreFactoryImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/state/impl/FlowCheckpointFactoryImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/state/impl/FlowCheckpointImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/state/impl/PipelineStateManager.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/factory/FlowFiberExecutionContextFactoryImplTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/handlers/events/SessionEventHandlerTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/handlers/events/StartFlowEventHandlerTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/service/InitiateFlowRequestServiceTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/sessions/CheckpointInitializerImplTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/sessions/impl/FlowProtocolStoreFactoryImplTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/state/FlowCheckpointImplTest.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/UtxoLedgerServiceImplTest.kt
  gradle.properties
  libs/flows/flow-api/src/main/kotlin/net/corda/flow/state/FlowCheckpoint.kt
  testing/ledger/ledger-common-base-integration-test/src/main/kotlin/net/corda/ledger/common/integration/test/CommonLedgerIntegrationTest.kt
Labels: enhancement
