Repository corda/corda-runtime-os, pull requests merged in 2023-11, with the labels that each got.

#5044 CORE-17966: Implement checkpoint cleanup handler when processing FlowFatalException
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/ExternalEventAcceptanceTest.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/SubFlowFailedAcceptanceTest.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/maintenance/CheckpointCleanupHandlerImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowEventExceptionProcessorImpl.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/impl/FlowEventExceptionProcessorImplTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/impl/FlowToBeKilledExceptionProcessingTest.kt
Labels: bug

#5071 CORE-18072 CORE-18263 fix resolveStateRef logic and call
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoPersistenceServiceImpl.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/persistence/UtxoLedgerStateQueryServiceImpl.kt
Labels: Stale

#5176 CORE-18457: Remove entity persistence duplication
  components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/external/events/AbstractPersistenceExternalEventFactory.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/external/events/FindAllExternalEventFactory.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/external/events/NamedQueryExternalEventFactory.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/persistence/external/events/AbstractPersistenceExternalEventFactoryTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/persistence/external/events/FindAllExternalEventFactoryTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/persistence/external/events/FindExternalEventFactoryTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/persistence/external/events/MergeExternalEventFactoryTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/persistence/external/events/NamedQueryExternalEventFactoryTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/persistence/external/events/PersistExternalEventFactoryTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/persistence/external/events/RemoveExternalEventFactoryTest.kt
  components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
  components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceServiceInternalTests.kt
  components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/helpers/Utils.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/EntityRequestSubscriptionFactoryImpl.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/FlowPersistenceServiceImpl.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityRequestProcessor.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/EntityRpcRequestProcessor.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/PersistenceServiceInternal.kt
  components/persistence/entity-processor-service-impl/src/main/kotlin/net/corda/entityprocessor/impl/internal/ProcessorService.kt
  components/persistence/entity-processor-service-impl/src/test/kotlin/net/corda/entityprocessor/impl/EntityRequestSubscriptionFactoryImplTest.kt
  components/persistence/entity-processor-service/src/main/kotlin/net/corda/entityprocessor/EntityRequestSubscriptionFactory.kt
  components/persistence/persistence-service-common/src/main/kotlin/net/corda/persistence/common/PayloadChecker.kt
  gradle.properties
  libs/flows/flow-api/src/main/kotlin/net/corda/flow/external/events/factory/ExternalEventRecord.kt
Labels: enhancement
