Repository corda/corda-runtime-os, pull requests merged in 2023-09, with the labels that each got.

#4528 CORE-15756 Segregated and Granular Corda Workers
  .ci/JenkinsfileSnykDelta
  .ci/PublishHelmChart/Jenkinsfile_PublishHelmChart
  .ci/e2eTests/Jenkinsfile
  .ci/e2eTests/JenkinsfileCombinedWorker
  .ci/e2eTests/JenkinsfileCombinedWorkerLinux
  .ci/e2eTests/JenkinsfileCombinedWorkerWindows
  .ci/e2eTests/JenkinsfileMultiClusterTest
  .ci/e2eTests/JenkinsfileUnstableTest
  .ci/e2eTests/corda.yaml
  .ci/e2eTests/ethereum/Jenkinsfile
  .ci/e2eTests/prereqs.yaml
  .ci/nightly/JenkinsfileNightly
  .ci/nightly/JenkinsfileSnykScan
  .ci/nightly/JenkinsfileUnstableTests
  .ci/nightly/JenkinsfileWindowsCompatibility
  .ci/versionCompatibility/Jenkinsfile
  .ci/versionCompatibility/latest-version.Jenkinsfile
  Jenkinsfile
  applications/workers/release/combined-worker/build.gradle
  applications/workers/release/combined-worker/src/main/kotlin/net/corda/applications/workers/combined/CombinedWorker.kt
  applications/workers/release/flow-mapper-worker/build.gradle
  applications/workers/release/flow-mapper-worker/detekt-baseline.xml
  applications/workers/release/flow-mapper-worker/src/main/kotlin/net.corda.applications.workers.flow.mapper/FlowMapperWorker.kt
  applications/workers/release/flow-mapper-worker/src/main/resources/log4j2.xml
  applications/workers/release/flow-worker/build.gradle
  applications/workers/release/flow-worker/src/main/kotlin/net/corda/applications/workers/flow/FlowWorker.kt
  applications/workers/release/persistence-worker/build.gradle
  applications/workers/release/persistence-worker/src/main/kotlin/net/corda/applications/workers/db/PersistenceWorker.kt
  applications/workers/release/rest-worker/src/e2eTest/resources/create.multi.clusters.sh
  applications/workers/release/rest-worker/src/e2eTest/resources/install.aws.sh
  applications/workers/release/verification-worker/build.gradle
  applications/workers/release/verification-worker/detekt-baseline.xml
  applications/workers/release/verification-worker/src/main/kotlin/net/corda/applications/workers/verification/VerificationWorker.kt
  applications/workers/release/verification-worker/src/main/resources/log4j2.xml
  applications/workers/workers-smoketest/build.gradle
  applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/ClusterBootstrapTest.kt
  charts/corda/templates/workers.yaml
  charts/corda/values.schema.json
  charts/corda/values.yaml
  components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/factory/SandboxDependencyInjectorFactoryImpl.kt
  gradle.properties
  processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
  processors/flow-mapper-processor/build.gradle
  processors/flow-mapper-processor/src/main/java/net.corda.processors.flow.mapper/package-info.java
  processors/flow-mapper-processor/src/main/kotlin/net.corda.processors.flow.mapper/FlowMapperProcessor.kt
  processors/flow-mapper-processor/src/main/kotlin/net.corda.processors.flow.mapper/internal/FlowMapperProcessorImpl.kt
  processors/flow-processor/build.gradle
  processors/flow-processor/src/main/kotlin/net/corda/processors/flow/internal/FlowProcessorImpl.kt
  processors/persistence-processor/build.gradle
  processors/persistence-processor/src/main/java/net/corda/processors/persistence/package-info.java
  processors/persistence-processor/src/main/kotlin/net/corda/processors/persistence/PersistenceProcessor.kt
  processors/persistence-processor/src/main/kotlin/net/corda/processors/persistence/internal/PersistenceProcessorImpl.kt
  processors/verification-processor/build.gradle
  processors/verification-processor/src/main/kotlin/net/corda/processors/verification/internal/VerificationProcessorImpl.kt
  settings.gradle
  tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckKafka.kt
  tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/CheckLimits.kt
  tools/plugins/preinstall/src/main/kotlin/net/corda/cli/plugins/preinstall/PreInstallPlugin.kt
  tools/plugins/preinstall/src/test/resources/KafkaTestSaslScram.yaml
  tools/plugins/topic-config/src/main/kotlin/net/corda/cli/plugins/topicconfig/Create.kt
Labels: Topology Redesign

#4574 CORE-16808: Create AWS CloudWatch SDK bundle for temporary use.
  applications/workers/worker-common/build.gradle
  applications/workers/worker-common/src/main/kotlin/net/corda/applications/workers/workercommon/internal/WorkerMonitorImpl.kt
  buildSrc/src/main/groovy/corda.common-app.gradle
  buildSrc/src/main/groovy/corda.common-library.gradle
  libs/awssdk/build.gradle
  settings.gradle
Labels: bug

#4582 CORE-14685: Update from Corda 5.1 up to fb9a468.
  buildSrc/README.md
  buildSrc/src/main/groovy/corda.java-only.gradle
  components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/external/events/FindAllExternalEventFactory.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/external/events/NamedQueryExternalEventFactory.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/application/persistence/query/ResultSetImpl.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/persistence/query/ResultSetImplTest.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/consensual/impl/AbstractConsensualQueryProvider.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/consensual/impl/ConsensualQueryProvider.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/consensual/impl/ConsensualRepositoryImpl.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/consensual/impl/PostgresConsensualQueryProvider.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/execution/impl/VaultNamedQueryExecutorImpl.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/Keywords.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/References.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/Tokens.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/VaultNamedQueryParserImpl.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/converters/AbstractVaultNamedQueryConverterImpl.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/converters/PostgresVaultNamedQueryConverter.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/expressions/VaultNamedQueryExpressionParser.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/expressions/VaultNamedQueryExpressionParserImpl.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/expressions/VaultNamedQueryExpressionValidator.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/query/parsing/expressions/VaultNamedQueryExpressionValidatorImpl.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/AbstractUtxoQueryProvider.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/PostgresUtxoQueryProvider.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoQueryProvider.kt
  components/ledger/ledger-persistence/src/main/kotlin/net/corda/ledger/persistence/utxo/impl/UtxoRepositoryImpl.kt
  components/ledger/ledger-persistence/src/test/kotlin/net/corda/ledger/persistence/query/impl/parsing/PostgresVaultNamedQueryParserIntegrationTest.kt
  components/ledger/ledger-persistence/src/test/kotlin/net/corda/ledger/persistence/query/impl/parsing/VaultNamedQueryParserImplTest.kt
  components/ledger/ledger-persistence/src/test/kotlin/net/corda/ledger/persistence/query/impl/parsing/converters/PostgresVaultNamedQueryConverterTest.kt
  components/ledger/ledger-persistence/src/test/kotlin/net/corda/ledger/persistence/query/impl/parsing/expressions/TokenTools.kt
  components/ledger/ledger-persistence/src/test/kotlin/net/corda/ledger/persistence/query/impl/parsing/expressions/VaultNamedQueryExpressionParserImplTest.kt
  components/ledger/ledger-persistence/src/test/kotlin/net/corda/ledger/persistence/query/impl/parsing/expressions/VaultNamedQueryExpressionValidatorImplTest.kt
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/flows/backchain/v1/TransactionBackchainReceiverFlowV1.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/backchain/v1/TransactionBackchainReceiverFlowV1Test.kt
  components/ledger/ledger-utxo-flow/src/test/kotlin/net/corda/ledger/utxo/flow/impl/flows/backchain/v2/TransactionBackchainReceiverFlowV2Test.kt
  components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
  components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/asyncoperation/handlers/VirtualNodeUpgradeOperationHandler.kt
  libs/awssdk/build.gradle
  libs/flows/flow-api/src/main/kotlin/net/corda/flow/persistence/query/ResultSetExecutor.kt
  notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/main/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImpl.kt
  notary-plugins/notary-plugin-non-validating/notary-plugin-non-validating-server/src/test/kotlin/com/r3/corda/notary/plugin/nonvalidating/server/NonValidatingNotaryServerFlowImplTest.kt
  testing/db-testkit/src/main/kotlin/net/corda/db/testkit/InMemoryEntityManagerConfiguration.kt
  testing/ledger/ledger-hsqldb/src/integrationTest/kotlin/net/corda/testing/ledger/tests/HsqldbVaultNamedQueryTest.kt
  testing/ledger/ledger-hsqldb/src/main/kotlin/net/corda/testing/ledger/consensual/HsqldbConsensualQueryProvider.kt
  testing/ledger/ledger-hsqldb/src/main/kotlin/net/corda/testing/ledger/query/HsqldbVaultNamedQueryConverter.kt
  testing/ledger/ledger-hsqldb/src/main/kotlin/net/corda/testing/ledger/query/Tokens.kt
  testing/ledger/ledger-hsqldb/src/main/kotlin/net/corda/testing/ledger/utxo/HsqldbUtxoQueryProvider.kt
  testing/ledger/ledger-hsqldb/src/test/kotlin/net/corda/testing/ledger/query/HsqldbVaultNamedQueryConverterTest.kt
  testing/ledger/ledger-hsqldb/src/test/kotlin/net/corda/testing/ledger/query/HsqldbVaultNamedQueryParserIntegrationTest.kt
Labels: Team's feature branch merge

#4590 CORE-16919: Move tracing implementation into :libs:tracing-impl module.
  applications/workers/release/combined-worker/build.gradle
  applications/workers/release/crypto-worker/build.gradle
  applications/workers/release/db-worker/build.gradle
  applications/workers/release/flow-mapper-worker/build.gradle
  applications/workers/release/flow-worker/build.gradle
  applications/workers/release/member-worker/build.gradle
  applications/workers/release/p2p-gateway-worker/build.gradle
  applications/workers/release/p2p-link-manager-worker/build.gradle
  applications/workers/release/persistence-worker/build.gradle
  applications/workers/release/rest-worker/build.gradle
  applications/workers/release/uniqueness-worker/build.gradle
  applications/workers/release/verification-worker/build.gradle
  libs/tracing-impl/build.gradle
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveBaggageFields.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveBatchPublishTracing.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveBatchRecordTracer.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveRecordTracing.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveTraceContext.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveTracingService.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveTracingServiceFactory.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/CombinedSpanReporter.kt
  libs/tracing/build.gradle
  libs/tracing/src/main/kotlin/net/corda/tracing/TraceThis.kt
  libs/tracing/src/main/kotlin/net/corda/tracing/TracingService.kt
  libs/tracing/src/main/kotlin/net/corda/tracing/TracingServiceFactory.kt
  libs/tracing/src/main/kotlin/net/corda/tracing/impl/NoopTracingService.kt
  settings.gradle
Labels: enhancement

#4608 CORE-14685: Merge from Corda 5.1 up to c3fc056.
  applications/workers/release/combined-worker/build.gradle
  applications/workers/release/crypto-worker/build.gradle
  applications/workers/release/db-worker/build.gradle
  applications/workers/release/flow-mapper-worker/build.gradle
  applications/workers/release/flow-worker/build.gradle
  applications/workers/release/member-worker/build.gradle
  applications/workers/release/p2p-gateway-worker/build.gradle
  applications/workers/release/p2p-link-manager-worker/build.gradle
  applications/workers/release/persistence-worker/build.gradle
  applications/workers/release/rest-worker/build.gradle
  applications/workers/release/uniqueness-worker/build.gradle
  applications/workers/release/verification-worker/build.gradle
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/SendAcceptanceTest.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/waiting/sessions/CounterpartyFlowInfoWaitingForHandler.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowExecutionPipelineStage.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImpl.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/handlers/waiting/sessions/CounterpartyFlowInfoWaitingForHandlerTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/impl/FlowExecutionPipelineStageTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/impl/FlowGlobalPostProcessorImplTest.kt
  components/membership/membership-p2p/src/main/kotlin/net/corda/membership/p2p/helpers/KeySpecExtractor.kt
  components/membership/membership-p2p/src/test/kotlin/net/corda/membership/p2p/helpers/KeySpecExtractorTest.kt
  components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/member/DynamicMemberRegistrationService.kt
  components/membership/registration-impl/src/test/kotlin/net/corda/membership/impl/registration/dynamic/member/DynamicMemberRegistrationServiceTest.kt
  libs/tracing-impl/build.gradle
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveBaggageFields.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveBatchPublishTracing.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveBatchRecordTracer.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveRecordTracing.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveTraceContext.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveTracingService.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/BraveTracingServiceFactory.kt
  libs/tracing-impl/src/main/kotlin/net/corda/tracing/brave/CombinedSpanReporter.kt
  libs/tracing/build.gradle
  libs/tracing/src/main/kotlin/net/corda/tracing/TraceThis.kt
  libs/tracing/src/main/kotlin/net/corda/tracing/TracingService.kt
  libs/tracing/src/main/kotlin/net/corda/tracing/TracingServiceFactory.kt
  libs/tracing/src/main/kotlin/net/corda/tracing/impl/NoopTracingService.kt
  libs/virtual-node/virtual-node-info/src/main/kotlin/net/corda/virtualnode/VirtualNodeInfo.kt
  settings.gradle
Labels: Team's feature branch merge

#4482 CORE-16184: SessionClose refactor
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/FlowMapperHelper.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/context/FlowServiceTestContext.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/context/StepSetup.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/CloseSessionsAcceptanceTest.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/InitiateFlowAcceptanceTest.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/ReceiveAcceptanceTest.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/SessionsAcceptanceTest.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/SubFlowFailedAcceptanceTest.kt
  components/flow/flow-service/src/integrationTest/kotlin/net/corda/flow/testing/tests/SubFlowFinishedAcceptanceTest.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/application/sessions/impl/FlowSessionImpl.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/SubFlowFinishedRequestHandler.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/CloseSessionsRequestHandler.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/service/CloseSessionService.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sessions/FlowSessionManager.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/pipeline/sessions/impl/FlowSessionManagerImpl.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/RequestHandlerTestContext.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/application/sessions/FlowSessionImplTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/handlers/requests/SubFlowFinishedRequestHandlerTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/CloseSessionsRequestHandlerTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/handlers/requests/sessions/service/CloseSessionServiceTest.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/pipeline/sessions/impl/FlowSessionManagerImplTest.kt
  libs/flows/flow-utils/src/main/kotlin/net/corda/flow/utils/FlowUtils.kt
  libs/flows/session-manager-impl/src/integrationTest/kotlin/net/corda/session/manager/integration/BusInteractions.kt
  libs/flows/session-manager-impl/src/integrationTest/kotlin/net/corda/session/manager/integration/MessageBus.kt
  libs/flows/session-manager-impl/src/integrationTest/kotlin/net/corda/session/manager/integration/SessionParty.kt
  libs/flows/session-manager-impl/src/integrationTest/kotlin/net/corda/session/manager/integration/SessionPartyFactory.kt
  libs/flows/session-manager-impl/src/integrationTest/kotlin/net/corda/session/manager/integration/helper/SessionEventGenerator.kt
  libs/flows/session-manager-impl/src/integrationTest/kotlin/net/corda/session/manager/integration/helper/SessionInteractionHelper.kt
  libs/flows/session-manager-impl/src/integrationTest/kotlin/net/corda/session/manager/integration/interactions/SessionCloseIntegrationTest.kt
  libs/flows/session-manager-impl/src/integrationTest/kotlin/net/corda/session/manager/integration/transition/SessionStateConfirmedTransitionTest.kt
  libs/flows/session-manager-impl/src/main/kotlin/net/corda/session/manager/impl/processor/SessionCloseProcessorReceive.kt
  libs/flows/session-manager-impl/src/main/kotlin/net/corda/session/manager/impl/processor/SessionCloseProcessorSend.kt
  libs/flows/session-manager-impl/src/main/kotlin/net/corda/session/manager/impl/processor/SessionDataProcessorSend.kt
  libs/flows/session-manager-impl/src/main/kotlin/net/corda/session/manager/impl/processor/helper/SessionProcessorHelper.kt
  libs/flows/session-manager-impl/src/test/kotlin/net/corda/session/manager/impl/processor/SessionCloseProcessorSendTest.kt
  processors/flow-processor/build.gradle
  processors/flow-processor/src/main/kotlin/net/corda/processors/flow/internal/FlowProcessorImpl.kt
  simulator/runtime/src/test/kotlin/net/corda/simulator/runtime/messaging/ConcurrentFlowMessagingTest.kt
  testing/cpbs/test-cordapp/src/main/kotlin/com/r3/corda/testing/smoketests/flow/RpcSmokeTestFlow.kt
  testing/flow/flow-utilities/src/main/kotlin/net/corda/test/flow/util/SessionHelper.kt
Labels: enhancement

#4614 CORE-17028: Upgrade to Quasar 0.9.1_r3-SNAPSHOT.
  build.gradle
  buildSrc/src/main/groovy/corda.quasar-app.gradle
  gradle.properties
Labels: enhancement

#4627 CORE-17074: Upgrade Kotlin Metadata 0.6.2 -> 0.7.0.
  gradle.properties
  libs/kotlin-reflection/build.gradle
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/impl/KotlinClassImpl.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/JavaProperty.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/JavaStaticProperty.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KPropertyInternal.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KotlinFunction.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KotlinMutableProperty1.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KotlinMutableProperty2.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KotlinProperty1.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KotlinProperty2.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KotlinTransientFunction.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KotlinType.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/KotlinTypeParameter.kt
  libs/kotlin-reflection/src/main/kotlin/net/corda/kotlin/reflect/types/TypeExtensions.kt
Labels: enhancement

#4674 CORE-16233 Implement Service APIs - DBWorker
  processors/db-processor/build.gradle
Labels: Topology Redesign

#4690 CORE-17300 Multi-SourceEventMediator - MessageBusConsumer
  libs/messaging/db-message-bus-impl/src/main/kotlin/net/corda/messagebus/db/consumer/DBCordaConsumerImpl.kt
  libs/messaging/kafka-message-bus-impl/src/main/kotlin/net/corda/messagebus/kafka/consumer/CordaKafkaConsumerImpl.kt
  libs/messaging/kafka-message-bus-impl/src/test/kotlin/net/corda/messagebus/kafka/consumer/CordaKafkaConsumerImplTest.kt
  libs/messaging/message-bus/src/main/kotlin/net/corda/messagebus/api/consumer/CordaConsumer.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/MessageBusConsumer.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/MessageBusConsumerTest.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/MediatorConsumer.kt
Labels: Topology Redesign

#4694 CORE-16200 Multi-Source Event Mediator configurations and factories
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/MediatorConsumerFactoryFactoryImpl.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/MessageBusClientFactory.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/MessageBusConsumerFactory.kt
  libs/messaging/messaging-impl/src/main/kotlin/net/corda/messaging/mediator/factory/MessagingClientFactoryFactoryImpl.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/factory/MediatorConsumerFactoryFactoryTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/factory/MessageBusClientFactoryTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/factory/MessageBusConsumerFactoryTest.kt
  libs/messaging/messaging-impl/src/test/kotlin/net/corda/messaging/mediator/factory/MessagingClientFactoryFactoryTest.kt
  libs/messaging/messaging/src/main/java/net/corda/messaging/api/mediator/config/package-info.java
  libs/messaging/messaging/src/main/java/net/corda/messaging/api/mediator/factory/package-info.java
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/config/MediatorConsumerConfig.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/config/MessagingClientConfig.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/factory/MediatorConsumerFactory.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/factory/MediatorConsumerFactoryFactory.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/factory/MessagingClientFactory.kt
  libs/messaging/messaging/src/main/kotlin/net/corda/messaging/api/mediator/factory/MessagingClientFactoryFactory.kt
Labels: Topology Redesign
