Repository corda/corda-runtime-os, pull requests merged in 2023-08, with the labels that each got.

#4407 CORE-15919: Deduce Corda API bundles instead of using hard-coded lists.
  build.gradle
  components/configuration/configuration-read-service-impl/test.bndrun
  components/flow/flow-p2p-filter-service/test.bndrun
  components/flow/flow-service/test.bndrun
  components/ledger/ledger-common-flow/test.bndrun
  components/ledger/ledger-consensual-flow/test.bndrun
  components/ledger/ledger-persistence/test.bndrun
  components/ledger/ledger-utxo-flow/test.bndrun
  components/ledger/ledger-verification/test.bndrun
  components/link-manager/test.bndrun
  components/membership/membership-group-read-impl/test.bndrun
  components/membership/membership-persistence-service-impl/test.bndrun
  components/membership/registration-impl/test.bndrun
  components/membership/synchronisation-impl/test.bndrun
  components/security-manager/test.bndrun
  components/uniqueness/uniqueness-checker-impl-osgi-tests/test.bndrun
  components/virtual-node/sandbox-group-context-service/src/main/kotlin/net/corda/sandboxgroupcontext/service/impl/SandboxGroupContextComponentImpl.kt
  components/virtual-node/sandbox-group-context-service/test.bndrun
  libs/application/addon-osgi-test/test.bndrun
  libs/configuration/configuration-osgi-test/test.bndrun
  libs/configuration/configuration-validation/test.bndrun
  libs/crypto/merkle-impl/test.bndrun
  libs/db/osgi-integration-tests/test.bndrun
  libs/flows/flow-mapper-impl/test.bndrun
  libs/kotlin-reflection/test.bndrun
  libs/layered-property-map/test.bndrun
  libs/permissions/permission-datamodel/test.bndrun
  libs/platform-info/test.bndrun
  libs/sandbox-internal/test.bndrun
  libs/serialization/serialization-amqp/test.bndrun
  libs/serialization/serialization-kryo/test.bndrun
  testing/sandboxes/src/main/kotlin/net/corda/testing/sandboxes/impl/SandboxSetupImpl.kt
  testing/sandboxes/test-api/build.gradle
Labels: enhancement

#4419 CORE-15959: Create an Antlr OSGi bundle specifically for Corda.
  build.gradle
  buildSrc/src/main/groovy/corda.common-library.gradle
  libs/antlr/build.gradle
  libs/db/db-orm-impl/build.gradle
  settings.gradle
Labels: enhancement

#4451 CORE-13893: Register sandbox eviction listener for StateAndRefCache.
  components/ledger/ledger-utxo-flow/src/main/kotlin/net/corda/ledger/utxo/flow/impl/cache/impl/StateAndRefCacheImpl.kt
Labels: bug

#4466 CORE-14685: Support for UTXO token cache.
  testing/db-testkit/src/main/kotlin/net/corda/db/testkit/InMemoryEntityManagerConfiguration.kt
  testing/driver/driver-engine/build.gradle
  testing/driver/driver-engine/src/main/java/net/corda/testing/driver/db/HsqldbJsonMetadataContributor.java
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/db/DbConnectionManagerImpl.kt
  testing/driver/driver-engine/src/main/kotlin/net/corda/testing/driver/processor/token/TokenCacheProcessor.kt
  testing/driver/driver-testing/src/integrationTest/kotlin/net/corda/testing/driver/tests/TokenBalanceQueryTests.kt
Labels: enhancement

#4468 CORE-16313: Upgrade Gradle 8.1.1 -> 8.2.1.
  build.gradle
  buildSrc/src/main/groovy/corda.common-library.gradle
  buildSrc/src/main/groovy/corda.osgi-test-conventions.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  libs/kotlin-reflection/build.gradle
  processors/member-processor/build.gradle
  testing/message-patterns/build.gradle
Labels: enhancement

#4481 CORE-14685: Only cache VirtualNodeInfo for members, not notaries.
  testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverDSLImpl.kt
Labels: bug

#4488 CORE-14685: Merge from Corda 5.1 up to 83f356f.
  applications/workers/workers-smoketest/src/smokeTest/kotlin/net/corda/applications/workers/smoketest/flow/FlowTests.kt
  components/flow/flow-service/src/main/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImpl.kt
  components/flow/flow-service/src/test/kotlin/net/corda/flow/external/events/impl/ExternalEventManagerImplTest.kt
  components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/StartRegistrationHandler.kt
  components/membership/registration-impl/src/main/kotlin/net/corda/membership/impl/registration/dynamic/member/DynamicMemberRegistrationService.kt
  components/membership/registration-impl/src/test/kotlin/net/corda/membership/impl/registration/dynamic/handler/mgm/StartRegistrationHandlerTest.kt
  components/membership/registration-impl/src/test/kotlin/net/corda/membership/impl/registration/dynamic/member/DynamicMemberRegistrationServiceTest.kt
  components/persistence/entity-processor-service-impl/src/integrationTest/kotlin/net/corda/entityprocessor/impl/tests/PersistenceExceptionTests.kt
  components/virtual-node/virtual-node-write-service-impl/build.gradle
  components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/VirtualNodeWriteServiceImpl.kt
  components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/VirtualNodeWriterFactory.kt
  components/virtual-node/virtual-node-write-service-impl/src/main/kotlin/net/corda/virtualnode/write/db/impl/writer/asyncoperation/handlers/VirtualNodeUpgradeOperationHandler.kt
  components/virtual-node/virtual-node-write-service-impl/src/test/kotlin/net/corda/virtualnode/write/db/impl/tests/writer/VirtualNodeWriterFactoryTests.kt
  components/virtual-node/virtual-node-write-service-impl/src/test/kotlin/net/corda/virtualnode/write/db/impl/tests/writer/asyncoperation/handlers/VirtualNodeUpgradeOperationHandlerTest.kt
  processors/db-processor/build.gradle
  processors/db-processor/src/main/kotlin/net/corda/processors/db/internal/DBProcessorImpl.kt
  testing/bundles/testing-dogs/src/main/kotlin/com/r3/corda/testing/bundles/dogs/VersionedDog.kt
  testing/bundles/testing-dogs/src/main/resources/dogs-without-pk.xml
  testing/bundles/testing-dogs/src/main/resources/versioned-dogs.xml
  testing/cpbs/test-cordapp/src/main/kotlin/com/r3/corda/testing/smoketests/flow/RpcSmokeTestFlow.kt
  testing/cpbs/test-cordapp/src/main/kotlin/com/r3/corda/testing/smoketests/flow/SendReceivePrimitiveMessagingFlow.kt
  testing/persistence-testkit/src/main/kotlin/net/corda/db/persistence/testkit/helpers/SandboxHelper.kt
  tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/AllowClientCertificate.kt
  tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/BaseOnboard.kt
  tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/GenerateGroupPolicy.kt
  tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/GroupParametersLookup.kt
  tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/MemberLookup.kt
  tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/OnBoardMember.kt
  tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/OnboardMgm.kt
  tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/README.md
  tools/plugins/network/src/main/kotlin/net/corda/cli/plugins/network/utils/PrintUtils.kt
  tools/plugins/plugins-rest/src/main/kotlin/net/corda/cli/plugins/common/RestClientUtils.kt
Labels: Team's feature branch merge

#4493 CORE-15179: Ensure vaultDml EntityManagerFactory always has its entities.
  components/ledger/ledger-utxo-token-cache/src/main/kotlin/net/corda/ledger/utxo/token/cache/services/AvailableTokenServiceImpl.kt
Labels: bug

#4164 CORE-15069 move flow to components
  components/flow/flow-mapper-impl/build.gradle
  components/flow/flow-mapper-impl/detekt-baseline.xml
  components/flow/flow-mapper-impl/src/integrationTest/kotlin/net/corda/flow/mapper/integration/FlowMapperIntegrationTest.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/FlowMapperEventExecutorFactoryImpl.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/ExecuteCleanupEventExecutor.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/FlowMapperHelper.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/ScheduleCleanupEventExecutor.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionErrorExecutor.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/StartFlowExecutor.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/FlowMapperEventExecutorFactoryImplTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/executor/ExecuteCleanupEventExecutorTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/executor/ScheduleCleanupEventExecutorTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/executor/SessionErrorExecutorTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutorTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutorTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/executor/StartFlowExecutorTest.kt
  components/flow/flow-mapper-impl/test.bndrun
  components/flow/flow-mapper-service/build.gradle
  components/flow/flow-mapper/build.gradle
  components/flow/flow-mapper/detekt-baseline.xml
  components/flow/flow-mapper/src/main/java/net/corda/flow/mapper/executor/package-info.java
  components/flow/flow-mapper/src/main/java/net/corda/flow/mapper/factory/package-info.java
  components/flow/flow-mapper/src/main/java/net/corda/flow/mapper/package-info.java
  components/flow/flow-mapper/src/main/kotlin/net/corda/flow/mapper/FlowMapperResult.kt
  components/flow/flow-mapper/src/main/kotlin/net/corda/flow/mapper/executor/FlowMapperEventExecutor.kt
  components/flow/flow-mapper/src/main/kotlin/net/corda/flow/mapper/factory/FlowMapperEventExecutorFactory.kt
  processors/flow-processor/build.gradle
  settings.gradle
Labels: enhancement

#4201 CORE-15070: use service to check if cluster is local
  components/flow/flow-mapper-impl/build.gradle
  components/flow/flow-mapper-impl/src/integrationTest/kotlin/net/corda/flow/mapper/integration/FlowMapperIntegrationTest.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/FlowMapperEventExecutorFactoryImpl.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/RecordFactoryImpl.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/FlowMapperHelper.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionErrorExecutor.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutor.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutor.kt
  components/flow/flow-mapper-impl/src/main/kotlin/net/corda/flow/mapper/impl/executor/Utils.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/FlowMapperEventExecutorFactoryImplTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/RecordFactoryImplTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/executor/SessionErrorExecutorTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/executor/SessionEventExecutorTest.kt
  components/flow/flow-mapper-impl/src/test/kotlin/net/corda/flow/mapper/impl/executor/SessionInitExecutorTest.kt
  components/flow/flow-mapper-impl/test.bndrun
  components/flow/flow-mapper-service/build.gradle
  components/flow/flow-mapper-service/src/integrationTest/kotlin/net/corda/session/mapper/service/integration/FlowMapperServiceIntegrationTest.kt
  components/flow/flow-mapper-service/src/main/kotlin/net/corda/session/mapper/service/FlowMapperService.kt
  components/flow/flow-mapper-service/src/main/kotlin/net/corda/session/mapper/service/executor/FlowMapperMessageProcessor.kt
  components/flow/flow-mapper/src/main/kotlin/net/corda/flow/mapper/factory/FlowMapperEventExecutorFactory.kt
  components/flow/flow-mapper/src/main/kotlin/net/corda/flow/mapper/factory/RecordFactory.kt
  components/membership/locally-hosted-identities-service-impl/build.gradle
  components/membership/locally-hosted-identities-service-impl/src/main/java/net/corda/membership/locally/hosted/identities/impl/package-info.java
  processors/flow-processor/build.gradle
  processors/flow-processor/src/main/kotlin/net/corda/processors/flow/internal/FlowProcessorImpl.kt
  testing/flow/flow-utilities/src/main/kotlin/net/corda/test/flow/util/SessionHelper.kt
Labels: enhancement

#4547 CORE-16798: Quasar to ignore ledger-utxo-data, SignedGroupParametersSerializer to platform serializer.
  libs/ledger/ledger-utxo-data/build.gradle
  libs/ledger/ledger-utxo-data/src/main/java/net/corda/ledger/utxo/data/package-info.java
  libs/ledger/ledger-utxo-data/src/main/kotlin/net/corda/ledger/utxo/data/groupparameters/serializer/amqp/SignedGroupParametersSerializer.kt
Labels: bug

#4553 CORE-14685: Add API for selecting node by group name and X500 name.
  testing/driver/driver-testing/src/test/java/net/corda/testing/driver/tests/DriverJavaTest.java
  testing/driver/src/main/java/net/corda/testing/driver/DriverDSL.java
  testing/driver/src/main/kotlin/net/corda/testing/driver/impl/DriverDSLImpl.kt
Labels: enhancement
